version: "3"

services:
  client:
    container_name: client
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    environment:
      - API_URL=http://server:8081/
    links:
      - server
      - server-database


  server:
    container_name: server
    build: ./server
    ports:
      - 8081:8081
    volumes:
      - ./server:/app
    depends_on: 
      - server-database
    environment:
      - DATABASE_URL=server-database:27017
    stdin_open: true
    tty: true

  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
volumes:
  mongo: